version: '3.8'

services:
  app:
    image: node:22
    container_name: meliodas
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: meliodas-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meliodas
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
